### ISSUE TITLE
Mouse Disappears

### ISSUE THREAD

**Issue by lordfarnam** [matt-m-o/YomiNinja#11]
Whenever I try to use the program on things like Persona 5 Royal or Star Ocean the Second, i'll hit printscreen and my mouse doesn't show. This makes it impossible to use yomininja. Do you know a fix for this? Thank you.

**Comment by matt-m-o** [comment]
I understand the issue, although I don't have access to Persona 5 Royal or Star Ocean on PC for testing. The video demos were recorded while capturing the Switch version of Persona 5.

I might have found a solution that worked well with other games that hide the mouse cursor.

When using borderless fullscreen, do the OCR boxes appear after pressing PrintScreen? Also, try pressing Alt+C (the hotkey to show the overlay) – does the cursor eventually show up over an OCR box if you move it around? Just to make sure I can reproduce the same issue.

Thanks.

**Comment by lordfarnam** [comment]
The boxes always appear when i press printscreen in both games. The games don't darken and my mouse "moves" i just don't have the ability to see where it is so i can't really move it to the boxes to look words up. This is what persona 5 looks like in windowed mode, borderless fullscreen, fullscreen.
![Screenshot 2023-12-13 073600](https://github.com/matt-m-o/YomiNinja/assets/42883401/7601d7a5-dde7-4d86-96f3-8c2e563c8104)

In the demo it looks like the screen sort of darkens like when you use microsoft snipping tool. Mine doesn't do that. I turned off discord and nvidia overlays too just in case.

**Comment by matt-m-o** [comment]
The OCR box background turning black on cursor hover is the only 'darkening' that is expected; anything else in the demo might be related to the video recording.
The fact that the OCR boxes are showing up is a good sign. However, the game might not only be hiding the cursor but also locking its position, which could be a concern.

I tested with Bayonetta, and despite the cursor being hidden by the game, moving the mouse with some patience allowed me to see the cursor when it hovered over a box.

Implementing a solution to solve this issue shouldn't be too difficult, as long as the game does not lock the cursor position. Otherwise, we will also have to find a way to unlock it.

<br>

Please follow these steps to determine if the game locks the cursor position:

1. Enable the Windows mouse option 'Show location of pointer when I press CTRL key'.
Settings > Devices > Mouse > Additional mouse options > Pointer Options tab
Check "Show location of pointer when I press CTRL key"

2. Hit Ctrl and you should see circles appearing around the cursor.

3. Run the game in borderless full screen.

4. Hit Ctrl while moving the mouse.

<br>
Let me know if the circles appear in different locations as you keep moving the mouse while hitting Ctrl.
Thanks for your patience.

**Comment by lordfarnam** [comment]
"I tested with Bayonetta, and despite the cursor being hidden by the game, moving the mouse with some patience allowed me to see the cursor when it hovered over a box." 

Persona 5: When in dialogue (first half of demo video) the mouse can move and i see the circles. When walking around (second half of demo video) the mouse is fixed and i only see circles in the center of the screen.

Star Ocean seems to just lock the mouse whether i'm walking around or in dialogue. I'll try to record a video of what i'm seeing to help but it might take a couple days.

**Comment by lordfarnam** [comment]
Here is a video that shows Yomininja settings>Star Ocean 2 Borderless and windowed> Persona 5 borderless and windowed: https://www.youtube.com/watch?v=DH3-1qdOKls

**Comment by matt-m-o** [comment]
Thanks for reporting this issue. Your video was very helpful in helping me understand the problem. I've implemented a solution, and it is now available in version v0.5.
I was able to test it on Star Ocean: The Second Story R Demo, and here is a video demonstrating the solution:

https://github.com/matt-m-o/YomiNinja/assets/25914763/cf4ab555-c3b0-44d6-922a-0ea6edfe3eea
