### ISSUE TITLE
Some OCR mismatches

### ISSUE THREAD

**Issue by madmalkav** [matt-m-o/YomiNinja#5]
![imagen](https://github.com/matt-m-o/YomiNinja/assets/11020793/9d9081c7-a980-47a8-811a-b4dbb16b7f35)

![imagen](https://github.com/matt-m-o/YomiNinja/assets/11020793/c3f9a9b0-62f0-4e57-b524-3eb36c384e6d)

As you can see, 喉 is mismatched and the OCR reads 候 , I looked on PaddleOCR japan_dict.txt and this kanji doesn't appear, may that be the source of the problem?

By the way, I tried the invert capture option, both inference runtimes and different precision settings, all throwing the same result.

**Comment by matt-m-o** [comment]
You're correct, it seems that this kanji wasn't included in the training data for the current OCR model used for Japanese, the latest one provided by PaddlePaddle. This might be because it's more commonly written in kana [のど]
Unfortunately, this issue can't be quickly resolved, as it would require training a custom model. However, once we implement support for other OCR engines like Google Lens/Cloud Vision, this problem should become less prominent.

**Comment by madmalkav** [comment]
This kanji was added to the list of Jouyou Kanji on 2010. IMHO recognizing all the Jouyou kanjis is basic for an OCR, so I will open a ticket for PaddleOCR (I’ll maybe try to see if there is some other Jouyou kanji missing in their model if I can figure out how to script that 😅)

in any case, out of YomiNinja scope, so feel free to close the ticket
